import type { Metadata } from "next";
import { site } from "@/lib/site";
import { PageHero } from "@/components/layout/page-hero";
import { Container, Section } from "@/components/ui/container";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of the TOBEEZ INTERIOR platform.",
};

const LAST_UPDATED = "13 July 2026";

const sections: { title: string; body: string[] }[] = [
  {
    title: "1. Agreement",
    body: [
      `These terms are an agreement between you and ${site.name} ("TOBEEZ", "we", "us"), operated from ${site.address}. By creating an account or using tobeezinteriors.com you accept these terms. If you do not agree, please do not use the platform.`,
    ],
  },
  {
    title: "2. The platform",
    body: [
      "TOBEEZ provides AI-assisted interior planning tools: a cost estimator, an AI design studio for chat, image, and video generation, expert consultation bookings, a curated product marketplace, and project dashboards. Features may change as the platform evolves.",
    ],
  },
  {
    title: "3. Estimates are planning ranges, not quotations",
    body: [
      "The AI Cost Estimator produces itemised planning ranges based on the details you provide and regional cost indices. Estimates are not binding supplier quotations, invoices, or professional valuations. Real project costs depend on site conditions, suppliers, and market movement. Always confirm final pricing with your suppliers or through a TOBEEZ consultation before committing money.",
    ],
  },
  {
    title: "4. AI-generated content",
    body: [
      "Designs, images, videos, and chat responses are generated by artificial intelligence. They are concepts for inspiration and planning — not architectural drawings, engineering documents, or professional advice. Generated visuals may contain inaccuracies, and products shown are conceptual unless clearly linked to a marketplace listing.",
      "You may use the visuals we generate for you in your own personal or commercial interior projects. You are responsible for the content you upload and must have the right to share any photos you submit.",
    ],
  },
  {
    title: "5. Subscriptions and payments",
    body: [
      "Studio Pro is a paid subscription (currently ₦43,000 per 30 days) that unlocks premium image and video generation, subject to fair-use generation limits per billing cycle. Subscriptions do not auto-renew — you choose when to renew.",
      "Consultations are paid per session at the price shown when booking (video and phone sessions, and in-person sessions at a higher rate). Estimator report unlocks are one-time payments.",
      "All payments are processed securely by Paystack. Except where required by law, fees are non-refundable once the paid service has been delivered — for example once generations have been used or a consultation has taken place. If something goes wrong with a payment, contact us and we will make it right.",
    ],
  },
  {
    title: "6. Consultations",
    body: [
      "Consultation bookings are confirmed for the date, time, and format you select. If you need to reschedule, contact us or your consultant as early as possible. Consultants provide professional guidance; decisions about your project and budget remain yours.",
    ],
  },
  {
    title: "7. Acceptable use",
    body: [
      "You agree not to: misuse the AI features (including attempts to generate unlawful, hateful, or infringing content); upload photos or content you have no right to use; attempt to bypass authentication, payment, or usage limits; disrupt the service or other users; or scrape the platform.",
      "We may suspend or terminate accounts that violate these terms.",
    ],
  },
  {
    title: "8. Your content and our platform",
    body: [
      "You keep ownership of the content you upload. You grant us the limited licence needed to operate the platform — for example sending your room photo to our AI providers to generate the redesign you requested.",
      "The platform itself — including its software, design, brand, and curated content — belongs to TOBEEZ and its licensors and may not be copied or resold.",
    ],
  },
  {
    title: "9. Disclaimers and liability",
    body: [
      "The platform is provided \"as is\". To the fullest extent permitted by law, we disclaim warranties of fitness for a particular purpose and do not guarantee uninterrupted or error-free service. Our total liability for any claim arising from the platform is limited to the amount you paid to TOBEEZ in the three months before the claim arose.",
    ],
  },
  {
    title: "10. Governing law and contact",
    body: [
      `These terms are governed by the laws of the Federal Republic of Nigeria. For questions, complaints, or notices, contact ${site.email} or ${site.phone}.`,
      "We may update these terms as the platform evolves; material changes will be posted on this page with a new \"last updated\" date.",
    ],
  },
];

export default function TermsPage() {
  return (
    <>
      <PageHero
        eyebrow="Legal"
        title="Terms of Service"
        description={`The rules of the road for using TOBEEZ. Last updated ${LAST_UPDATED}.`}
      />
      <Section>
        <Container className="max-w-3xl space-y-10">
          {sections.map((section) => (
            <div key={section.title}>
              <h2 className="font-display text-xl font-semibold">{section.title}</h2>
              {section.body.map((paragraph) => (
                <p key={paragraph.slice(0, 40)} className="mt-3 text-sm leading-7 text-muted-foreground">
                  {paragraph}
                </p>
              ))}
            </div>
          ))}
        </Container>
      </Section>
    </>
  );
}
