-- TOBEEZ INTERIORS — real consultation bookings and consultant availability.
-- Apply this migration together with 0002_user_data.sql in the Supabase SQL editor.

create table if not exists public.consultant_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  consultant_id text not null check (consultant_id in ('d1', 'd2')),
  created_at timestamptz not null default now(),
  unique (consultant_id)
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  client_user_id uuid not null references auth.users(id) on delete cascade,
  consultant_id text not null check (consultant_id in ('d1', 'd2')),
  client_name text not null,
  client_email text not null,
  type text not null,
  mode text not null check (mode in ('virtual', 'phone', 'physical')),
  date_iso date not null,
  time text not null check (time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  amount integer not null check (amount > 0),
  paystack_ref text not null unique,
  status text not null default 'pending'
    check (status in ('pending', 'confirmed', 'declined', 'completed', 'cancelled')),
  notes text not null default '',
  created_at timestamptz not null default now()
);

-- A pending or confirmed appointment owns its consultant/date/time slot.
create unique index if not exists bookings_active_slot_unique
  on public.bookings (consultant_id, date_iso, time)
  where status in ('pending', 'confirmed');

create index if not exists bookings_client_created_idx
  on public.bookings (client_user_id, created_at desc);
create index if not exists bookings_consultant_schedule_idx
  on public.bookings (consultant_id, date_iso, time);

create table if not exists public.consultant_availability (
  id bigint generated by default as identity primary key,
  consultant_id text not null check (consultant_id in ('d1', 'd2')),
  date_iso date,
  weekday smallint check (weekday between 0 and 6),
  slots jsonb not null default '[]'::jsonb check (jsonb_typeof(slots) = 'array'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((date_iso is not null and weekday is null) or (date_iso is null and weekday is not null))
);

create unique index if not exists consultant_availability_date_unique
  on public.consultant_availability (consultant_id, date_iso)
  where date_iso is not null;
create unique index if not exists consultant_availability_weekday_unique
  on public.consultant_availability (consultant_id, weekday)
  where weekday is not null;

alter table public.consultant_users enable row level security;
alter table public.bookings enable row level security;
alter table public.consultant_availability enable row level security;

drop policy if exists "consultants read own mapping" on public.consultant_users;
create policy "consultants read own mapping" on public.consultant_users
  for select using (auth.uid() = user_id);

drop policy if exists "clients read own bookings" on public.bookings;
create policy "clients read own bookings" on public.bookings
  for select using (auth.uid() = client_user_id);

drop policy if exists "consultants read addressed bookings" on public.bookings;
create policy "consultants read addressed bookings" on public.bookings
  for select using (
    exists (
      select 1 from public.consultant_users cu
      where cu.user_id = auth.uid() and cu.consultant_id = bookings.consultant_id
    )
  );

-- State changes are performed through transition_consultation_booking below;
-- this RLS rule still records the addressed-row boundary at the table layer.
drop policy if exists "consultants update addressed bookings" on public.bookings;
create policy "consultants update addressed bookings" on public.bookings
  for update using (
    exists (
      select 1 from public.consultant_users cu
      where cu.user_id = auth.uid() and cu.consultant_id = bookings.consultant_id
    )
  ) with check (
    exists (
      select 1 from public.consultant_users cu
      where cu.user_id = auth.uid() and cu.consultant_id = bookings.consultant_id
    )
  );

drop policy if exists "consultants manage own availability" on public.consultant_availability;
create policy "consultants manage own availability" on public.consultant_availability
  for all using (
    exists (
      select 1 from public.consultant_users cu
      where cu.user_id = auth.uid()
        and cu.consultant_id = consultant_availability.consultant_id
    )
  ) with check (
    exists (
      select 1 from public.consultant_users cu
      where cu.user_id = auth.uid()
        and cu.consultant_id = consultant_availability.consultant_id
    )
  );

-- Direct booking inserts and arbitrary updates stay closed. The functions below
-- derive the client/consultant identity from auth.uid() and constrain mutations.
revoke insert, update, delete on public.bookings from anon, authenticated;
grant select on public.bookings to authenticated;
grant select on public.consultant_users to authenticated;
grant select, insert, update, delete on public.consultant_availability to authenticated;
grant usage, select on sequence public.consultant_availability_id_seq to authenticated;

create or replace function public.create_consultation_booking(
  p_consultant_id text,
  p_client_name text,
  p_client_email text,
  p_type text,
  p_mode text,
  p_date_iso date,
  p_time text,
  p_amount integer,
  p_paystack_ref text,
  p_notes text default ''
)
returns setof public.bookings
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  expected_amount integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;
  if p_consultant_id not in ('d1', 'd2') then
    raise exception 'Unknown consultant' using errcode = '22023';
  end if;
  expected_amount := case p_mode
    when 'virtual' then 100000
    when 'phone' then 100000
    when 'physical' then 150000
    else null
  end;
  if expected_amount is null or p_amount <> expected_amount then
    raise exception 'Invalid consultation amount' using errcode = '22023';
  end if;

  return query
  insert into public.bookings (
    client_user_id, consultant_id, client_name, client_email, type, mode,
    date_iso, time, amount, paystack_ref, status, notes
  ) values (
    auth.uid(), p_consultant_id, trim(p_client_name), lower(trim(p_client_email)),
    trim(p_type), p_mode, p_date_iso, p_time, p_amount, trim(p_paystack_ref),
    'pending', coalesce(trim(p_notes), '')
  )
  returning *;
end;
$$;

revoke all on function public.create_consultation_booking(text, text, text, text, text, date, text, integer, text, text) from public, anon;
grant execute on function public.create_consultation_booking(text, text, text, text, text, date, text, integer, text, text) to authenticated;

create or replace function public.transition_consultation_booking(
  p_booking_id uuid,
  p_action text
)
returns setof public.bookings
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  booking_row public.bookings%rowtype;
  mapped_consultant text;
  next_status text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  select * into booking_row from public.bookings where id = p_booking_id for update;
  if not found then
    raise exception 'Booking not found' using errcode = 'P0002';
  end if;

  select consultant_id into mapped_consultant
  from public.consultant_users where user_id = auth.uid();

  if p_action in ('accept', 'decline', 'complete') then
    if mapped_consultant is distinct from booking_row.consultant_id then
      raise exception 'Consultant access required' using errcode = '42501';
    end if;
    if p_action in ('accept', 'decline') and booking_row.status <> 'pending' then
      raise exception 'Booking is no longer pending' using errcode = '55000';
    end if;
    if p_action = 'complete' and booking_row.status <> 'confirmed' then
      raise exception 'Only confirmed bookings can be completed' using errcode = '55000';
    end if;
    next_status := case p_action
      when 'accept' then 'confirmed'
      when 'decline' then 'declined'
      else 'completed'
    end;
  elsif p_action = 'cancel' then
    if booking_row.client_user_id <> auth.uid() then
      raise exception 'Client access required' using errcode = '42501';
    end if;
    if booking_row.status not in ('pending', 'confirmed') then
      raise exception 'Booking cannot be cancelled' using errcode = '55000';
    end if;
    next_status := 'cancelled';
  else
    raise exception 'Invalid booking action' using errcode = '22023';
  end if;

  return query
  update public.bookings set status = next_status where id = p_booking_id
  returning *;
end;
$$;

revoke all on function public.transition_consultation_booking(uuid, text) from public, anon;
grant execute on function public.transition_consultation_booking(uuid, text) to authenticated;

-- Public booking calendars receive only open dates/slots. Client identity,
-- notes, payment references, and booking records never leave this function.
create or replace function public.get_consultant_availability(
  p_consultant_id text,
  p_from date,
  p_to date
)
returns table (date_iso date, slots jsonb)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with calendar as (
    select day::date as date_iso
    from generate_series(p_from::timestamp, p_to::timestamp, interval '1 day') day
    where p_to >= p_from and p_to - p_from <= 62
  ), configured as (
    select
      calendar.date_iso,
      coalesce(specific.slots, weekly.slots) as configured_slots
    from calendar
    left join lateral (
      select ca.slots
      from public.consultant_availability ca
      where ca.consultant_id = p_consultant_id and ca.date_iso = calendar.date_iso
      limit 1
    ) specific on true
    left join lateral (
      select ca.slots
      from public.consultant_availability ca
      where ca.consultant_id = p_consultant_id
        and ca.weekday = extract(dow from calendar.date_iso)::smallint
      limit 1
    ) weekly on true
  )
  select
    configured.date_iso,
    coalesce(
      jsonb_agg(to_jsonb(slot.value) order by slot.value)
        filter (where slot.value is not null and not exists (
          select 1 from public.bookings b
          where b.consultant_id = p_consultant_id
            and b.date_iso = configured.date_iso
            and b.time = slot.value
            and b.status in ('pending', 'confirmed')
        )),
      '[]'::jsonb
    ) as slots
  from configured
  left join lateral jsonb_array_elements_text(configured.configured_slots) slot(value) on true
  where configured.configured_slots is not null
  group by configured.date_iso
  order by configured.date_iso;
$$;

revoke all on function public.get_consultant_availability(text, date, date) from public;
grant execute on function public.get_consultant_availability(text, date, date) to anon, authenticated;

comment on table public.consultant_users is
  'Map Supabase auth users to d1 (Victory) or d2 (Joy). Seed rows by hand after the consultants create accounts.';
comment on table public.bookings is
  'Authoritative consultation bookings. Application creation is Paystack-verified server-side before calling the constrained insert function.';
